### ISSUE TITLE
Add event listener directly to the MediaQueryList 

### ISSUE THREAD

**Issue by omasback** [bence-toth/react-hook-media-query#2]
instead of window resize events. I just found this out looking at some other media hooks on npm that do the same thing.

**Comment by bence-toth** [comment]
@omasback, this sounds like a good idea, is this a change you would be interested in implementing? Feel free to open a PR. :slightly_smiling_face:

**Comment by bence-toth** [comment]
For clarity: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

**Comment by bence-toth** [comment]
Resolved by #3
